import 'dart:io';

import '../subscription/vless_proxy.dart';

/// Generates a Mihomo (clash-meta) `config.yaml` from a parsed proxy list.
///
/// We do not pull in a YAML emitter — Mihomo is robust to plain string output
/// and this gives us full control over field ordering and quoting.
class ConfigWriter {
  static Future<void> writeConfig({
    required String path,
    required List<VlessProxy> proxies,
    required bool tun,
    int mixedPort = 7890,
    int controllerPort = 9090,
    String? secret,
    String mode = 'rule',
  }) async {
    final sb = StringBuffer();

    sb.writeln('# Generated by Kiss VPN — do not edit by hand.');
    sb.writeln('mixed-port: $mixedPort');
    sb.writeln('allow-lan: false');
    sb.writeln('mode: $mode');
    sb.writeln('log-level: info');
    sb.writeln('ipv6: false');
    sb.writeln('external-controller: 127.0.0.1:$controllerPort');
    if (secret != null && secret.isNotEmpty) {
      sb.writeln('secret: "$secret"');
    }
    sb.writeln('geodata-mode: true');
    sb.writeln('geo-auto-update: false');
    sb.writeln();

    sb.writeln('dns:');
    sb.writeln('  enable: true');
    sb.writeln('  listen: 127.0.0.1:1053');
    sb.writeln('  ipv6: false');
    sb.writeln('  enhanced-mode: fake-ip');
    sb.writeln('  fake-ip-range: 198.18.0.1/16');
    sb.writeln('  nameserver:');
    sb.writeln('    - 1.1.1.1');
    sb.writeln('    - 8.8.8.8');
    sb.writeln();

    if (tun) {
      sb.writeln('tun:');
      sb.writeln('  enable: true');
      sb.writeln('  stack: system');
      sb.writeln('  dns-hijack:');
      sb.writeln('    - any:53');
      sb.writeln('  auto-route: true');
      sb.writeln('  auto-detect-interface: true');
      sb.writeln();
    }

    sb.writeln('proxies:');
    for (final px in proxies) {
      _emitProxy(sb, px);
    }
    sb.writeln();

    final names = proxies.map((p) => p.name).toList();

    sb.writeln('proxy-groups:');
    sb.writeln('  - name: Proxy');
    sb.writeln('    type: select');
    sb.writeln('    proxies:');
    sb.writeln('      - Auto');
    for (final n in names) {
      sb.writeln('      - ${_quote(n)}');
    }
    sb.writeln('  - name: Auto');
    sb.writeln('    type: url-test');
    sb.writeln('    url: https://www.gstatic.com/generate_204');
    sb.writeln('    interval: 300');
    sb.writeln('    tolerance: 50');
    sb.writeln('    proxies:');
    for (final n in names) {
      sb.writeln('      - ${_quote(n)}');
    }
    sb.writeln();

    sb.writeln('rules:');
    sb.writeln('  - DOMAIN-SUFFIX,kissmain.ru,DIRECT');
    sb.writeln('  - GEOIP,LAN,DIRECT');
    sb.writeln('  - GEOIP,RU,DIRECT');
    sb.writeln('  - MATCH,Proxy');

    final f = File(path);
    await f.parent.create(recursive: true);
    await f.writeAsString(sb.toString());
  }

  static void _emitProxy(StringBuffer sb, VlessProxy p) {
    sb.writeln('  - name: ${_quote(p.name)}');
    sb.writeln('    type: vless');
    sb.writeln('    server: ${p.server}');
    sb.writeln('    port: ${p.port}');
    sb.writeln('    uuid: ${p.uuid}');
    sb.writeln('    udp: true');
    sb.writeln('    network: ${p.network}');
    if (p.flow != null) sb.writeln('    flow: ${p.flow}');
    if (p.tls) sb.writeln('    tls: true');
    if (p.sni != null) sb.writeln('    servername: ${p.sni}');
    if (p.fingerprint != null) {
      sb.writeln('    client-fingerprint: ${p.fingerprint}');
    }
    if (p.realityPublicKey != null) {
      sb.writeln('    reality-opts:');
      sb.writeln('      public-key: ${p.realityPublicKey}');
      if (p.realityShortId != null) {
        sb.writeln('      short-id: ${p.realityShortId}');
      }
    }
    if (p.network == 'ws' && p.wsPath != null) {
      sb.writeln('    ws-opts:');
      sb.writeln('      path: ${p.wsPath}');
      if (p.wsHost != null) {
        sb.writeln('      headers:');
        sb.writeln('        Host: ${p.wsHost}');
      }
    }
    if (p.network == 'grpc' && p.grpcServiceName != null) {
      sb.writeln('    grpc-opts:');
      sb.writeln('      grpc-service-name: ${p.grpcServiceName}');
    }
  }

  static String _quote(String s) {
    // Quote names that contain YAML-special chars, whitespace, or any
    // non-ASCII characters (the latter covers flag emojis in server names).
    final special = RegExp(r"[\s:#&*!|>%@\[\]{}'""]|[^\x00-\x7F]");
    if (special.hasMatch(s)) {
      return '"${s.replaceAll('"', '\\"')}"';
    }
    return s;
  }
}
